### ISSUE TITLE
Cannot build this project on Windows use vs2015

### ISSUE THREAD

**Issue by toby20130333** [edwardstock/bip3x#1]
Hello @edwardstock 

I got the follew error when build this projcet on windows

xx\nem.h:30: error: C1083: cannot open : “ed25519-donna/ed25519.h”: No such file or directory

**Comment by edwardstock** [comment]
Hi @toby20130333 ! This project is not fully completed, and some original sources was removed to reduce library size. I didn't have time to check all things is working. These includes are not using in main project, and if you are trying to generate mnemonic, you could look at `src/main.cpp` (here are examples how it works)

**Comment by edwardstock** [comment]
Hi there, again! If this info is actual for you, i have removed all unused references, and you can try to use lib again.

**Comment by toby20130333** [comment]
@edwardstock thanks
