### ISSUE TITLE
Error when bip3x::HDKeyEncoder::makeExtendedKey

### ISSUE THREAD

**Issue by Lavshyak** [edwardstock/bip3x#11]
`
    #include "bip3x/Bip39Mnemonic.h"
    #include "bip3x/HDKeyEncoder.h"
    #include <iostream>

    using namespace std;
    using namespace bip3x;
    using namespace toolbox;

    int main(int argc, char **argv) {

    cout << "start" << endl;

    auto mnemonic = bip3x::Bip39Mnemonic::generate();
    auto root = HDKeyEncoder::makeBip32RootKey(mnemonic.raw);

    Derivation derivation("m’/44’/60’/0’/0");
    bip3x::HDKeyEncoder::makeExtendedKey(root, derivation); //here<<<<<<<<<<<<<<<<

    return 0;
    }
`

utils.h row 34:
`BIP39_CORE_API uint32_t str_to_uint32_t(std::string const& str, size_t* idx = 0, int base = 10);` //idx = 0

utils.cpp row 17:
`unsigned long result = std::stoul(str, idx, base);` - here idx = NULL.
error: terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoul

**Comment by edwardstock** [comment]
Hi @Lavshyak ! 
There is a mistake in your code.
Derivation path has wrong format: hardening can't be added to the **m**: 

Use `m/44'/60'/0'/0` instead `m'/44'/60'/0'/0`
