### ISSUE TITLE
can't install on windows (even w/ -DENABLE_CONAN=OFF)

### ISSUE THREAD

**Issue by Phildo** [edwardstock/bip3x#3]
The commands I'm running are:

```
git clone git@github.com:edwardstock/bip3x
cd bip3x
git submodule update --init --recursive
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Debug -DENABLE_CONAN=OFF -DCMAKE_INSTALL_PREFIX="C:\Users\phild\projects\bipinst" 
```

and I'm getting
```
CMake Error at modules/ConanInit.cmake:1 (find_program):                                                                                                                      Could not find CONAN_BIN using the following names: conan 
```
as a result.

(This probably isn't helpful, but some additional info:
Just on a whim, I went in and commented out `#find_program(CONAN_BIN conan REQUIRED)` in `modules\ConanInit.cmake`, and now I'm getting an error that `FindToolbox.cmake` isn't found.)

**Comment by edwardstock** [comment]
Hi @Phildo ! Yep, it was my mistake, i've fixed finding conan if it disabled. 
Also, i don't use anymore submodules as dependencies (only gtest left), as it leads to incosistence in recursive dependencies.
So, to build bip3x manually, you should build toolbox manually too.

How to build toolbox:
- get toolbox `https://github.com/edwardstock/toolbox.git`
- configure ` cmake .. -DCMAKE_BUILD_TYPE=Release -DENABLE_CONAN=Off -DCMAKE_INSTALL_PREFIX=C:/libs/toolbox`
- build `cmake --build .`
- install `cmake --build . --target install`

Now to build bip3x you need to pass -DToolbox_ROOT=C:/libs/toolbox while configuring project
- configure `cmake .. -DCMAKE_BUILD_TYPE=Release -DToolbox_ROOT=C:/libs/toolbox` -DCMAKE_INSTALL_PREFIX=C:/libs/bip3x
- and so on...

**Comment by cavernec** [comment]
Hi @edwardstock ! 

Following your above procedure yields to the following error message :

**CMake Warning:
  Manually-specified variables were not used by the project:
  Toolbox_ROOT**

Would you know why ? It looks like one can't override the path manually...

Thanks !
