### ISSUE TITLE
return Value of HDKeyEncoder::makeExtendendKey is void?

### ISSUE THREAD

**Issue by dpalmetz** [edwardstock/bip3x#4]
Hi!
I am trying to use your library and I have a problem in using HDKeyEncoder::makeExtendedKey.
In the header-file the return type is defined as void, but should it not return a HDKey?

**Comment by edwardstock** [comment]
Hi @dpalmetz ! Yes, `makeExtendedKey` modifies source `HDKey` by reference because it uses root key data. See example here:
https://github.com/edwardstock/bip3x/blob/master/tests/minter_cxx_test.cpp

If you need a copy of `HDKey`, u can make it by yourself and pass it by reference to `makeExtendedKey`:
```cpp
HDKey root = HDKeyEncoder::makeBip32RootKey(seed, bip3x::MainNet);
HDKey derivedKey = root;
HDKeyEncoded::makeExtendedKey(derivedKey, "m/44'/60'/0'/0/0");
```

**Comment by dpalmetz** [comment]
> Hi @dpalmetz ! Yes, `makeExtendedKey` modifies source `HDKey` by reference because it uses root key data. See example here:
> https://github.com/edwardstock/bip3x/blob/master/tests/minter_cxx_test.cpp
> 
> If you need a copy of `HDKey`, u can make it by yourself and pass it by reference to `makeExtendedKey`:
> 
> ```c++
> HDKey root = HDKeyEncoder::makeBip32RootKey(seed, bip3x::MainNet);
> HDKey derivedKey = root;
> HDKeyEncoded::makeExtendedKey(derivedKey, "m/44'/60'/0'/0/0");
> ```

Ah,  ok. Thanks for the hint. I looked at the examples at the readme.md, and there it says:
`HDKey ethereumKey = HDKeyEncoder::makeExtendedKey(bip32RootKey, "m/44'/60'/0'/0");`

Thanks for your answer, now it works!

**Comment by edwardstock** [comment]
Fixed readme. Thank you!
https://github.com/edwardstock/bip3x/commit/a2c4c45a011506e13c1b2f06d811c63e4b8ac331

**Comment by dpalmetz** [comment]
> Fixed readme. Thank you!
> [a2c4c45](https://github.com/edwardstock/bip3x/commit/a2c4c45a011506e13c1b2f06d811c63e4b8ac331)

Thank for fixing it. This is a very good library. I wanted to understand a little bit what is going on under the surface with address-generation. Your library made it really easy for me to start with all this.

Thanks for sharing your nice work!
