### ISSUE TITLE
Generating ethereum addresses from HDKey ?

### ISSUE THREAD

**Issue by cavernec** [edwardstock/bip3x#5]
Hi Eduard, hope you're doing well.

It looks like your library used to implement functions to get addresses (see https://github.com/edwardstock/bip3x/blob/master/src/main.cpp#L71) but I can't find such things with the current version. Am I missing something ?

Anyway thank you very much for sharing your code, this is a very useful lib !

**Comment by edwardstock** [comment]
Hi @cavernec ! Yes, you're right. Library does not support generating eth address as it requires full implementation of secp256k1.

Example how to create valid public key you can see here:
https://github.com/edwardstock/native-secp256k1-java/blob/7cd4aeddd4ccf96d6d69e9d46b8d2b6e0c33ad02/src/java/NativeSecp256k1.cpp#L187

And how to generate address here:
https://github.com/MinterTeam/cpp-minter/blob/3dc9bc864eb3f78711a2c4ad163e97c9a74e2cf1/src/data/address.cpp#L57
But this example not related directly to ethereum, as it used for another BC and of course, you need to get all related functions (such as sha256 keccak256) to do what you need
