### ISSUE TITLE
Bip39 windows issue

### ISSUE THREAD

**Issue by itamarcps** [edwardstock/bip3x#6]
Be aware that the current generation of bip32 keys for MinGW is **not secure**. It uses time as its seed and std::mt19937 (not secure for cryptographic usage) which can be potentially catastrophic and easily recreated with some coding.
https://github.com/edwardstock/bip3x/blob/master/src/minter/Bip39Mnemonic.cpp#L44

If you are looking to use this library and have the availability of OpenSSL, please look towards my fork.

**Comment by edwardstock** [comment]
Hi @itamarcps ! I've added ability to build library with openssl random (`-DUSE_OPENSSL_RANDOM` https://github.com/edwardstock/bip3x/commit/588df274e6ea8581b32f1abd55853a14587049f8)

**Comment by itamarcps** [comment]
Please leave a notice for users that have the avaibility to use OpenSSL, as it is much more secure than using a time seeded randomness.
Problem solved, thanks for your attention

> 
> 
> Hi @itamarcps ! I've added ability to build library with openssl random (`-DUSE_OPENSSL_RANDOM` [588df27](https://github.com/edwardstock/bip3x/commit/588df274e6ea8581b32f1abd55853a14587049f8))

**Comment by edwardstock** [comment]
@itamarcps already https://github.com/edwardstock/bip3x#cross-compile-for-windows-under-mingw64
Next time, when I update the readme, I will point this case specifically for gcc and mingw on windows
