### ISSUE TITLE
no digital signature.

### ISSUE THREAD

**Issue by WaGeLaiNa** [edwardstock/bip3x#9]
E: The repository "https://edwardstock.jfrog.io/artifactory/debian{distribution}InRelease" has no digital signature.

**Comment by WaGeLaiNa** [comment]
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal

**Comment by lukintrees** [comment]
curl -s https://edwardstock.jfrog.io/artifactory/api/gpg/key/public | sudo apt-key add -

**Comment by edwardstock** [comment]
I will no longer upload distribution packages. In the future, I may publish them to GitHub, but that step has not been taken yet.
